import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <div className="flex min-h-screen flex-1 flex-col pb-7">
          <main className="flex-1">{children}</main>
          <footer className="fixed bottom-0 left-0 right-0 border-t border-slate-200/30 py-1.5 text-center text-xs text-slate-400 print:hidden">
            Inspired by 교원성장메이트(강주원) | Crafted by shingu.es
          </footer>
        </div>
      </body>
    </html>
  );
}
